name: word_master
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.1
  realm: ^3.4.1
  rxdart: ^0.28.0
  selectable: ^0.3.2
  uuid: ^4.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
